### ISSUE TITLE
mutimc pls pls support it

### ISSUE THREAD

**Issue by wickedcody123456** [WcAServices/AltDispenser_issues#12]
a been meaning to use mutimc but i cant with this alts

**Comment by NGTmeaty** [comment]
We will look into this.

**Comment by mcjp78** [comment]
Where does MultiMC store alts? In json, txt, where? Will need this to support

**Comment by wickedcody123456** [comment]
when a get back to my main pc a will check in to it sorry for taking forever

**Comment by JorgenVatle** [comment]
You should be able to use our new Alt Credentials feature for logging into alts with MultiMC.
