### ISSUE TITLE
Fix your shit

### ISSUE THREAD

**Issue by skjfblka** [WcAServices/AltDispenser_issues#14]
Alty will not even open, I'm on widows 10. It worked for almost a week then just one day stopped opening, didn't change anything.

**Comment by JorgenVatle** [comment]
Could you launch Alty through your command prompt and provide us with any output given upon doing so? 😄 

If you're unsure how to do this, create a `.bat` file with the following contents.
```
java -jar Alty.jar
```
Ensure that Alty is named exactly `Alty.jar` and that the `.bat` file is located in the same folder as Alty.
