### ISSUE TITLE
Alts from alt-dispenser!

### ISSUE THREAD

**Issue by darkdna1738** [WcAServices/AltDispenser_issues#15]
Why all of the sudden is alt-dispenser not authenticated with minecraft.net!!!! I cant ever just play a server without my two favorite servers being banned which is hypixel and mineplex and you guys rarely refresh alts and it's so annoying i mite go get a diff gen this shit is getting annoying!!!

**Comment by NGTmeaty** [comment]
Hey 👏 We work very hard to get unbanned alts everyone. For the hypixel problem, we are looking into it. The banned alts problem, new alts come every 5 minutes, so this should be solved by waiting.
