### ISSUE TITLE
Please open the Authenticator and switch to Mojang's authentication servers. 

### ISSUE THREAD

**Issue by Muff1nMan600** [WcAServices/AltDispenser_issues#17]
The title is the error message I receive when i try and log into my regular account. I have the new launcher because there really wasn't a choice when upgrading. I feel like this is really easy to fix and that I probably did something wrong. Please get back to me as soon as you can with answers to my problem

**Comment by NGTmeaty** [comment]
https://help.altdispenser.net/alty/i-cannot-use-my-main-account
