### ISSUE TITLE
Private Alts

### ISSUE THREAD

**Issue by NGTmeaty** [WcAServices/AltDispenser_issues#2]
http://image.prntscr.com/image/9f7977cdd77c4498b904e3446f40eeac.png

The last private alt on the list does not seem to want to be able to be removed.

**Comment by Warthelm** [comment]
Does refreshing the page temporarily correct the issue?

**Comment by NGTmeaty** [comment]
It does now, thanks so much.

**Comment by ItzOnlyAnimalYT** [comment]
`` why'd you re open it? ``

**Comment by Warthelm** [comment]
Refreshing the page only serves as a temporary fix. It is still an issue that should be looked into on our end. My apologies for not clarifying that.

**Comment by JorgenVatle** [comment]
Issue has been tested and resolved.
