### ISSUE TITLE
Alty not working with new minecraft launcher

### ISSUE THREAD

**Issue by Spxboy** [WcAServices/AltDispenser_issues#9]
Title. It worked before the new launcher came out.

**Comment by NGTmeaty** [comment]
What's not working about it?

**Comment by Spxboy** [comment]
The alt name shows up as **hidden** and I can only play the demo.

**Comment by Freshest123** [comment]
It wont work for me either its honestly pissing me off

**Comment by NGTmeaty** [comment]
If you go into C: -> Users -> (your username). If you delete the AltDispenser folder, this will fix the issue.

**Comment by telkthesingle** [comment]
Same problem as @Freshest123 when i deleted the file it doesnt fix the demo issue

**Comment by telkthesingle** [comment]
@NGTmeaty it still shows demo after ive deleted the folder

**Comment by JorgenVatle** [comment]
There should be a fix out for this.

Can you ensure that you're using Alty version 0.4.3 and try again? 😄

**Comment by mcjp78** [comment]
I believe its been officially fixed  (With a breaking change), could you re run alty?

**Comment by JorgenVatle** [comment]
This should be fixed now.
